## PRE ##
## PRE ##

[meta]
keywords = ['peter', 'varo', 'petervaro', 'engineer', 'designer', 'github',
            'stackoverflow', 'offsetof', 'sketchandprototype', 'rust', 'c', 'd',
            'python', 'py', 'javascript', 'js', 'typescript', 'ts', 'go',
            'poetry', 'cargo', 'crate', 'c++', 'cpp', 'cxx', 'software', 'bash',
            'sh', 'haskell', 'unix', 'linux', 'gnu', 'free', 'open', 'source',
            'cv', 'resume', 'developer', 'software', 'libre']

[info]
name = 'Peter Varo'
